#define BOX_SPATIAL_DIMENSION 1
#define BOX_PERIODIC 
#define HYDRO_MESHLESS_FINITE_MASS 
#define HYDRO_PRESSURE_SPH 
#define EOS_GAMMA (5.0/3.0)
#define SELFGRAVITY_OFF 
#define OUTPUT_IN_DOUBLEPRECISION 
#define INPUT_IN_DOUBLEPRECISION 
