# Select Target Computer
#
# Please copy this file to Makefile.systype and uncomment your
# system. Don't commit changes to this file unless you add support for
# a new system.
#
#############

#SYSTYPE="github-ubuntu"
#SYSTYPE="Frontera"
#SYSTYPE="MacBookCellar"
SYSTYPE="MacBookCellar_Kokkos"
#SYSTYPE="Vista"
#SYSTYPE="Expanse"
#SYSTYPE="CaltechHPC"
#SYSTYPE="RUSTY"
#SYSTYPE="Frontier"       # OLCF, MI250X via the Kokkos HIP backend
#SYSTYPE="Frontier_CPU"   # OLCF, same source dispatched to the Kokkos OpenMP backend
#SYSTYPE="Lonestar6"      # TACC, A100 via the Kokkos CUDA backend (Kokkos built per user: see Makefile)
#SYSTYPE="Lonestar6_CPU"  # TACC, same source dispatched to the Kokkos OpenMP backend
